### ISSUE TITLE
Reduce The SPACE 

### ISSUE THREAD

**Issue by Vijaykv5** [flashohq/flasho#2]
![Capture](https://user-images.githubusercontent.com/94985341/220175893-d6f54fbf-ace8-4156-805c-babfe0ee7efc.PNG)

Space at the bottom(Footer) can be reduced. Overall it looks good in the mobile vie , In Desktop version it can be reduced

**Comment by vishnau31** [comment]
The issue has been fixed. You can check @ https://www.flasho.io
